import type { Metadata } from "next";
import "./globals.css";
import "../assets/css/nucleo-icons.css";
import "../assets/css/nucleo-svg.css";
import "../assets/css/soft-ui-dashboard-tailwind.css";
import Head from "next/head";
import PerfectScrollbar from "perfect-scrollbar";
import "perfect-scrollbar/css/perfect-scrollbar.css";

export const metadata: Metadata = {
  title: "RS PKU Muhammadiyah Boja",
  description: "Generated by Fadh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (typeof window !== "undefined") {
    document.addEventListener("DOMContentLoaded", function () {
      if (document.querySelectorAll(".overflow-auto")[0]) {
        var elements = document.querySelectorAll(".overflow-auto");
        elements.forEach((element) => {
          new PerfectScrollbar(element);
        });
      }
      if (document.querySelectorAll(".overflow-y-auto")[0]) {
        var elements = document.querySelectorAll(".overflow-y-auto");
        elements.forEach((element) => {
          new PerfectScrollbar(element);
        });
      }
      if (document.querySelectorAll(".overflow-x-auto")[0]) {
        var elements = document.querySelectorAll(".overflow-x-auto");
        elements.forEach((element) => {
          new PerfectScrollbar(element);
        });
      }
    });
  }
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body
        className={`m-0 font-sans text-base antialiased font-normal leading-default bg-gray-50 text-slate-500`}
      >
        {children}
      </body>
    </html>
  );
}
